
// This file has been generated by the GUI designer. Do not modify.
namespace Proyecto
{
	public partial class NuevoForm
	{
		private global::Gtk.Fixed fixed7;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Proyecto.NuevoForm
			this.Name = "Proyecto.NuevoForm";
			this.Title = global::Mono.Unix.Catalog.GetString ("NuevoForm");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Proyecto.NuevoForm.Gtk.Container+ContainerChild
			this.fixed7 = new global::Gtk.Fixed ();
			this.fixed7.Name = "fixed7";
			this.fixed7.HasWindow = false;
			this.Add (this.fixed7);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 823;
			this.DefaultHeight = 561;
			this.Show ();
		}
	}
}
