
// This file has been generated by the GUI designer. Do not modify.
namespace Proyecto
{
	public partial class mailForm
	{
		private global::Gtk.Fixed fixed3;
		private global::Gtk.Label label1;
		private global::Gtk.Entry Para;
		private global::Gtk.Entry Asunto;
		private global::Gtk.Label label2;
		private global::Gtk.Button Enviar;
		private global::Gtk.Entry Body;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Proyecto.mailForm
			this.Name = "Proyecto.mailForm";
			this.Title = global::Mono.Unix.Catalog.GetString ("mailForm");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Proyecto.mailForm.Gtk.Container+ContainerChild
			this.fixed3 = new global::Gtk.Fixed ();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Para:");
			this.fixed3.Add (this.label1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.label1]));
			w1.X = 100;
			w1.Y = 60;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.Para = new global::Gtk.Entry ();
			this.Para.CanFocus = true;
			this.Para.Name = "Para";
			this.Para.IsEditable = true;
			this.Para.InvisibleChar = '●';
			this.fixed3.Add (this.Para);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.Para]));
			w2.X = 140;
			w2.Y = 55;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.Asunto = new global::Gtk.Entry ();
			this.Asunto.CanFocus = true;
			this.Asunto.Name = "Asunto";
			this.Asunto.IsEditable = true;
			this.Asunto.InvisibleChar = '●';
			this.fixed3.Add (this.Asunto);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.Asunto]));
			w3.X = 145;
			w3.Y = 102;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Asunto");
			this.fixed3.Add (this.label2);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.label2]));
			w4.X = 95;
			w4.Y = 108;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.Enviar = new global::Gtk.Button ();
			this.Enviar.CanFocus = true;
			this.Enviar.Name = "Enviar";
			this.Enviar.UseUnderline = true;
			this.Enviar.Label = global::Mono.Unix.Catalog.GetString ("Enviar");
			this.fixed3.Add (this.Enviar);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.Enviar]));
			w5.X = 583;
			w5.Y = 385;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.Body = new global::Gtk.Entry ();
			this.Body.WidthRequest = 400;
			this.Body.HeightRequest = 200;
			this.Body.CanFocus = true;
			this.Body.Name = "Body";
			this.Body.IsEditable = true;
			this.Body.InvisibleChar = '●';
			this.fixed3.Add (this.Body);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.Body]));
			w6.X = 104;
			w6.Y = 153;
			this.Add (this.fixed3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 660;
			this.DefaultHeight = 429;
			this.Show ();
			this.Enviar.Clicked += new global::System.EventHandler (this.OnEnviarClicked);
		}
	}
}
